#!/usr/bin/python3

from optparse import OptionParser
import os
import sys
import apt

pkg_dicts = {}

def debug_print(debug, msg):
    if debug:
        print(msg)

def main():
    parser = OptionParser("%prog")
    parser.add_option(
        "--v", default=False, action="store_true",
        help="enable debugging", dest="enable_debug")    
    options, _ = parser.parse_args()
    debug_print(options.enable_debug, "Enable debugging option")

    with open('bionic-classic-arch.list', 'r', encoding='UTF-8') as input:
        for line in input:
            temp = line[:-1]
            package = temp.split('*')
            arch = package[1]
            pkg_dicts[package[0]] = arch[1:-4]

    with open('bionic-classic-apt.list', 'w') as out:
        with open('bionic-classic-pkgname.list', 'r', encoding='UTF-8') as file:
            for line in file:
                cache = apt.Cache()
                temp = line[:-1]
                try:
                    pkg_name = temp
                    apt_pkg = cache[pkg_name]
                    ver = apt_pkg.candidate
                    pkg_info = str(ver).split('=')
                    if ":" not in pkg_info[1]:
                        pkg_file = pkg_name + '_' + pkg_info[1] + '_' + pkg_dicts[pkg_name] +".deb" 
                    else:
                        pkg_file = pkg_name + '_' + pkg_info[1].split(':')[1] + '_' + pkg_dicts[pkg_name] +".deb"
                    out.write(pkg_file + '\n')
                except KeyError as err:
                    if pkg_name == "linux-headers-4.15.0-":
                        pkg_file = pkg_name + "*_all.deb"
                        debug_print(options.enable_debug, "can't find: "+pkg_file)
                        out.write(pkg_file + '\n')
                    elif pkg_name == "linux-headers-4.15.0-*-generic" or \
                            pkg_name == "linux-modules-4.15.0-*-generic" or pkg_name == "linux-modules-extra-4.15.0-*-generic" or \
                            pkg_name == "linux-image-4.15.0-*-generic" or pkg_name == "linux-image-extra-4.15.0-*-generic" or \
                            pkg_name == "linux-signed-image-4.15.0-*-generic":
                        pkg_file = pkg_name + "*_amd64.deb"
                        debug_print(options.enable_debug, "can't find: "+pkg_file)
                        out.write(pkg_file + '\n')
                    else:
                        debug_print(options.enable_debug, "can't find: "+pkg_name)
                        out.write(line)

if __name__ == "__main__":
    main()
